name: App
fileGroups:
  - README.md
options:
  developmentLanguage: ja
  xcodeVersion: 11.5
config:
  Debug: debug
  Release: release
targets:
  App:
    type: application
    platform: iOS
    developmentTarget: 13.0
    sources:
      - path: App
    scheme: {}
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: AV9FQ3YF56
        PRODUCT_BUNDLE_IDENTIFIER: com.tomoki-sun.app.ios.App
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          INFOPLIST_FILE: App/Resources/Info/Debug.plist
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          INFOPLIST_FILE: App/Resources/Info/Release.plist
  AppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: AppTests
    dependencies:
      - target: App
    scheme:
      gatherCoverageData: true
      testTargets:
        - AppTests
