name: CI

on:
  push:
    paths-ignore:
      - Docs/**
      - README.md

env:
  DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: macOS-latest
    env:
      MINT_PATH: mint/lib
      MINT_LINK_PATH: mint/bin

    steps:
    - uses: actions/checkout@v2

    - name: Install Mint
      run: brew install mint

    - name: Cache Mint packages
      uses: actions/cache@v2
      with:
        path: mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    - name: Generate Xcode project with XcodeGen
      run: mint run xcodegen xcodegen generate

    - name: iOS test
      run: |
        set -o pipefail
        xcodebuild build-for-testing test-without-building -project Template.xcodeproj -scheme TemplateTests -configuration Debug -sdk iphonesimulator -destination "name=iPhone 8" ENABLE_TESTABILITY=YES | xcpretty -c

    - name: codecov
      run: bash <(curl -s https://codecov.io/bash)
      if: success()
