name: CI

on:
  pull_request:
    paths:
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}